# Generated by Django 5.2.1 on 2026-03-20 03:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('device_type', models.CharField(choices=[('controller', 'Controller'), ('fan', 'Fan'), ('pump', 'Pump'), ('light', 'Light')], max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='offline', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('api_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_on', models.BooleanField(default=False)),
                ('desired_on', models.BooleanField(default=False)),
                ('last_command', models.CharField(blank=True, max_length=50)),
                ('last_value', models.CharField(blank=True, max_length=50)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='api.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('light', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soil_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['recorded_at'], name='sensor_recorded_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThresholdRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('light', 'Light'), ('soil_moisture', 'Soil Moisture')], max_length=20)),
                ('condition', models.CharField(choices=[('lte', '<='), ('gte', '>=')], max_length=5)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('action_type', models.CharField(choices=[('alert_only', 'Alert only'), ('toggle_device', 'Toggle device'), ('set_device', 'Set device')], default='alert_only', max_length=20)),
                ('target_value', models.CharField(blank=True, max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('cooldown_seconds', models.PositiveIntegerField(default=300)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('message_template', models.CharField(blank=True, max_length=255)),
                ('target_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='api.device')),
            ],
            options={
                'ordering': ['metric', 'condition', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='warning', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('happened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='api.device')),
                ('sensor_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='api.sensordata')),
                ('source_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='api.thresholdrule')),
            ],
            options={
                'ordering': ['-happened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ack', 'Acknowledged'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='api.device')),
            ],
            options={
                'ordering': ['status', '-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='cmd_status_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='thresholdrule',
            index=models.Index(fields=['metric', 'enabled'], name='rule_metric_enabled_idx'),
        ),
    ]
