# Generated by Django 5.2.1 on 2026-04-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_controlstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlState',
        ),
        migrations.RemoveField(
            model_name='thresholdrule',
            name='target_device',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='source_rule',
        ),
        migrations.DeleteModel(
            name='SensorCurrent',
        ),
        migrations.DeleteModel(
            name='ThresholdRule',
        ),
    ]
