# Generated by Django 5.2.1 on 2026-04-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_controlstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.CharField(default='main', max_length=20, unique=True)),
                ('mode', models.CharField(choices=[('AUTO', 'AUTO'), ('MANUAL', 'MANUAL')], default='MANUAL', max_length=10)),
                ('manual_reason', models.CharField(blank=True, max_length=255)),
                ('manual_changed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Control state',
                'verbose_name_plural': 'Control state',
            },
        ),
    ]
