# Generated by Django 4.2.16 on 2026-05-09 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_controlstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.CharField(default='main', max_length=20, unique=True)),
                ('crop_name', models.CharField(default='Default crop', max_length=100)),
                ('crop_kc', models.FloatField(default=1.0)),
                ('target_low', models.FloatField(default=55.0)),
                ('target_high', models.FloatField(default=65.0)),
                ('step_seconds', models.PositiveIntegerField(default=300)),
                ('horizon_steps', models.PositiveIntegerField(default=12)),
                ('pump_min_seconds', models.FloatField(default=0.0)),
                ('pump_max_seconds', models.FloatField(default=300.0)),
                ('pump_grid_seconds', models.FloatField(default=30.0)),
                ('soft_daily_pump_cap_seconds', models.FloatField(default=1800.0)),
                ('weight_band', models.FloatField(default=10.0)),
                ('weight_water', models.FloatField(default=0.2)),
                ('weight_switch', models.FloatField(default=0.5)),
                ('weight_daily', models.FloatField(default=2.0)),
                ('weight_terminal', models.FloatField(default=20.0)),
                ('adaptive_enabled', models.BooleanField(default=True)),
                ('adaptive_bias_window', models.PositiveIntegerField(default=12)),
                ('adaptive_max_abs_bias', models.FloatField(default=5.0)),
                ('stale_after_seconds', models.PositiveIntegerField(default=600)),
                ('actuator_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Control profile',
                'verbose_name_plural': 'Control profile',
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('controller', 'Controller'), ('fan', 'Fan'), ('pump', 'Pump'), ('light', 'Light'), ('mist', 'Mist')], max_length=20),
        ),
        migrations.CreateModel(
            name='EstimationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_ts', models.DateTimeField(db_index=True)),
                ('cycle_index', models.PositiveIntegerField(db_index=True)),
                ('validation_status', models.CharField(blank=True, max_length=32)),
                ('validation_reason', models.TextField(blank=True)),
                ('preprocess_status', models.CharField(choices=[('valid', 'Valid'), ('skipped', 'Skipped')], default='skipped', max_length=20)),
                ('cycle_status', models.CharField(choices=[('ok', 'OK'), ('skipped_no_measurement', 'Skipped no measurement'), ('error', 'Error')], default='error', max_length=40)),
                ('adaptive_status', models.CharField(choices=[('R_updated', 'R updated'), ('R_skipped', 'R skipped'), ('skipped', 'Skipped')], default='skipped', max_length=20)),
                ('raw_soil_moisture', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('light', models.FloatField(blank=True, null=True)),
                ('drip', models.FloatField(blank=True, null=True)),
                ('mist', models.FloatField(blank=True, null=True)),
                ('fan', models.FloatField(blank=True, null=True)),
                ('arx_predicted', models.FloatField(blank=True, null=True)),
                ('kf_x_prior', models.FloatField(blank=True, null=True)),
                ('kf_P_prior', models.FloatField(blank=True, null=True)),
                ('kf_innovation', models.FloatField(blank=True, null=True)),
                ('kf_R', models.FloatField(blank=True, null=True)),
                ('kf_K', models.FloatField(blank=True, null=True)),
                ('kf_x_posterior', models.FloatField(blank=True, null=True)),
                ('kf_P_posterior', models.FloatField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('sensor_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimation', to='api.sensordata')),
            ],
            options={
                'ordering': ['-sample_ts', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AMPCRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(default='MANUAL', max_length=10)),
                ('pump_seconds', models.FloatField(default=0.0)),
                ('step_seconds', models.PositiveIntegerField(default=300)),
                ('predicted_soil_moisture', models.JSONField(blank=True, default=list)),
                ('target_band', models.JSONField(blank=True, default=dict)),
                ('objective_cost', models.FloatField(default=0.0)),
                ('safety_status', models.CharField(default='pump_off_failsafe', max_length=40)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('bias_correction', models.FloatField(default=0.0)),
                ('bias_window_count', models.PositiveIntegerField(default=0)),
                ('used_today_pump_seconds', models.FloatField(default=0.0)),
                ('command_created', models.BooleanField(default=False)),
                ('actuator_status', models.CharField(choices=[('disabled', 'Disabled'), ('not_called', 'Not called'), ('queued', 'Queued'), ('device_not_found', 'Device not found'), ('unsafe_skipped', 'Unsafe skipped')], default='not_called', max_length=30)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('state_snapshot', models.JSONField(blank=True, default=dict)),
                ('device_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ampc_recommendations', to='api.devicecommand')),
                ('estimation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ampc_recommendations', to='api.estimationcycle')),
                ('sensor_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ampc_recommendations', to='api.sensordata')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='estimationcycle',
            index=models.Index(fields=['sample_ts', 'id'], name='est_sample_id_idx'),
        ),
        migrations.AddIndex(
            model_name='estimationcycle',
            index=models.Index(fields=['cycle_status', 'sample_ts'], name='est_status_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='ampcrecommendation',
            index=models.Index(fields=['created_at', 'safety_status'], name='ampc_created_safety_idx'),
        ),
    ]
