# Generated by Django 4.2.16 on 2026-05-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ampc_scheduler_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='depletion_fraction_p',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='irrigation_area_m2',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='latitude',
            field=models.FloatField(default=16.0471),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='longitude',
            field=models.FloatField(default=108.2068),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='pump_efficiency',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='pump_flow_lps',
            field=models.FloatField(default=0.02),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='root_depth_m',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='soil_type',
            field=models.CharField(choices=[('sand', 'Sand'), ('light_loam', 'Light Loam'), ('loam', 'Loam'), ('clay_loam', 'Clay Loam')], default='loam', max_length=32),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='theta_fc',
            field=models.FloatField(default=0.32),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='theta_sat',
            field=models.FloatField(default=0.45),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='theta_wp',
            field=models.FloatField(default=0.15),
        ),
    ]
