# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_fao56_control_profile_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(
                fields=('greenhouse', 'code'),
                name='uq_device_greenhouse_code',
            ),
        ),
    ]
