from django.urls import path
from .views import (
    AlertListView,
    AlertMarkAllReadView,
    AlertMarkReadView,
    ChartView,
    ControlModeView,
    ControlStateView,
    DashboardOverviewView,
    DeviceCommandView,
    DeviceListView,
    DeviceToggleView,
    IngestCommandAckView,
    IngestHeartbeatView,
    IngestPendingCommandsView,
    IngestReadingsView,
    LatestReadingView,
    LoginView,
    RuleDetailView,
    RuleListView,
)

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('dashboard/overview/', DashboardOverviewView.as_view(), name='dashboard-overview'),
    path('control/state/', ControlStateView.as_view(), name='control-state'),
    path('control/mode/', ControlModeView.as_view(), name='control-mode'),
    path('sensor-readings/latest/', LatestReadingView.as_view(), name='sensor-latest'),
    path('sensor-readings/chart/', ChartView.as_view(), name='sensor-chart'),
    path('devices/', DeviceListView.as_view(), name='device-list'),
    path('devices/<int:pk>/toggle/', DeviceToggleView.as_view(), name='device-toggle'),
    path('devices/<int:pk>/command/', DeviceCommandView.as_view(), name='device-command'),
    path('alerts/', AlertListView.as_view(), name='alert-list'),
    path('alerts/<int:pk>/mark_read/', AlertMarkReadView.as_view(), name='alert-mark-read'),
    path('alerts/mark_all_read/', AlertMarkAllReadView.as_view(), name='alert-mark-all-read'),
    path('rules/', RuleListView.as_view(), name='rule-list'),
    path('rules/<int:pk>/', RuleDetailView.as_view(), name='rule-detail'),
    path('ingest/readings/', IngestReadingsView.as_view(), name='ingest-readings'),
    path('ingest/heartbeat/', IngestHeartbeatView.as_view(), name='ingest-heartbeat'),
    path('ingest/commands/pending/', IngestPendingCommandsView.as_view(), name='ingest-pending-commands'),
    path('ingest/commands/<int:pk>/ack/', IngestCommandAckView.as_view(), name='ingest-command-ack'),
]