from django.urls import path
from .views import (
    AlertListView,
    AlertMarkAllReadView,
    AlertMarkReadView,
    AMPCSchedulerStartView,
    AMPCSchedulerStopView,
    AMPCSchedulerView,
    AutoRecommendationView,
    AutoSettingsView,
    ChartView,
    ControlModeView,
    ControlStateView,
    DashboardOverviewView,
    DeviceCommandView,
    DeviceListView,
    DeviceToggleView,
    ForecastView,
    IngestCommandAckView,
    IngestHeartbeatView,
    IngestPendingCommandsView,
    IngestReadingsView,
    GreenhouseAMPCRecommendationView,
    GreenhouseAMPCLatestRecommendationView,
    GreenhouseControlProfileView,
    LatestReadingView,
    LiveIngestSamplesView,
    LoginView,
    RunListView,
    RunMetricsView,
    RunSeriesView,
    SensorHistoryView,
)

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('dashboard/overview/', DashboardOverviewView.as_view(), name='dashboard-overview'),
    path('sensor-readings/latest/', LatestReadingView.as_view(), name='sensor-latest'),
    path('sensor-readings/chart/', ChartView.as_view(), name='sensor-chart'),
    path('sensor-readings/history/', SensorHistoryView.as_view(), name='sensor-history'),
    path('control/state/', ControlStateView.as_view(), name='control-state'),
    path('control/mode/', ControlModeView.as_view(), name='control-mode'),
    path('forecast/', ForecastView.as_view(), name='forecast'),
    path('auto-settings/', AutoSettingsView.as_view(), name='auto-settings'),
    path('control/auto-recommendation/', AutoRecommendationView.as_view(), name='auto-recommendation'),
    path('control/ampc-scheduler/', AMPCSchedulerView.as_view(), name='ampc-scheduler'),
    path('control/ampc-scheduler/start/', AMPCSchedulerStartView.as_view(), name='ampc-scheduler-start'),
    path('control/ampc-scheduler/stop/', AMPCSchedulerStopView.as_view(), name='ampc-scheduler-stop'),
    path('runs/', RunListView.as_view(), name='run-list'),
    path('runs/<int:run_id>/series/', RunSeriesView.as_view(), name='run-series'),
    path('runs/<int:run_id>/metrics/', RunMetricsView.as_view(), name='run-metrics'),
    path('greenhouses/<int:greenhouse_id>/control-profile/', GreenhouseControlProfileView.as_view(), name='greenhouse-control-profile'),
    path('greenhouses/<int:greenhouse_id>/ampc/recommendations/', GreenhouseAMPCRecommendationView.as_view(), name='greenhouse-ampc-recommendation'),
    path('greenhouses/<int:greenhouse_id>/ampc/recommendations/latest/', GreenhouseAMPCLatestRecommendationView.as_view(), name='greenhouse-ampc-latest-recommendation'),
    path('devices/', DeviceListView.as_view(), name='device-list'),
    path('devices/<int:pk>/toggle/', DeviceToggleView.as_view(), name='device-toggle'),
    path('devices/<int:pk>/command/', DeviceCommandView.as_view(), name='device-command'),
    path('alerts/', AlertListView.as_view(), name='alert-list'),
    path('alerts/<int:pk>/mark_read/', AlertMarkReadView.as_view(), name='alert-mark-read'),
    path('alerts/mark_all_read/', AlertMarkAllReadView.as_view(), name='alert-mark-all-read'),
    path('ingest/readings/', IngestReadingsView.as_view(), name='ingest-readings'),
    path('ingest/samples/', LiveIngestSamplesView.as_view(), name='ingest-samples'),
    path('ingest/heartbeat/', IngestHeartbeatView.as_view(), name='ingest-heartbeat'),
    path('ingest/commands/pending/', IngestPendingCommandsView.as_view(), name='ingest-pending-commands'),
    path('ingest/commands/<int:pk>/ack/', IngestCommandAckView.as_view(), name='ingest-command-ack'),
]
